Repository Group-02-CS3043/AspireTrust, pull requests merged in 2023-11, with the labels that each got.

#55 added account creation for new users
  BankAccount/bank_account.py
  Database/connection.py
  Database/database_quaries.py
  templates/bankAccount/displayCreatedAccount.html
Labels: documentation, upgrade

#57 changing the color in contact us section and changing the content in …
  static/css/home.css
  templates/home/home.html
Labels: bug, enhancement, upgrade

#61 added physical loan site
  static/css/physical_loan.css
  templates/dashboard/employee_dashboard.html
  templates/loan/physical_loan.html
Labels: enhancement, upgrade

#63 loan installment page added
  static/css/loan_installment.css
  templates/loan/loan_installment.html
  templates/loan_installment.html
Labels: enhancement

#64 All the account creation pages are working without error
  Auth/auth.py
  BankAccount/bank_account.py
  BankAccount/transaction.py
  Configurations/Error_handler.py
  Database/database_quaries.py
  Home/home.py
  Loan/loan.py
  Reports/report.py
  User/user.py
  templates/bankAccount/displayCreatedAccount.html
  templates/bankAccount/existingUserCreateMain.html
  templates/bankAccount/newUserCreationMain.html
  templates/dashboard/customer_dashboard.html
  templates/dashboard/manager_dashbaord.html
  templates/home/home.html
  templates/loan/loanRequest.html
  templates/reports/allwithdraws.html
  templates/serverError.html
  templates/user_details.html
Labels: enhancement, upgrade
